kind: ConfigMap
apiVersion: v1
metadata:
  name: observability-metrics-custom-whitelist
  namespace: open-cluster-management-observability
data:
  metrics_list.yaml: |
    names:
      - node_memory_Active_bytes
