{
 "title": "Kubernetes Persistent Volumes",
 "tags": [
  "persistent volumes",
  "kubernetes"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kubelet_volume_stats_capacity_bytes, namespace)"
   },
   { "name": "capacity", "label": "Capacity", "query": "50,60,70,80,90,95" }
  ]
 },
 "panels": [
  {
   "title": "Number of PVCs > $capacity% Used",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum((((kubelet_volume_stats_capacity_bytes-kubelet_volume_stats_available_bytes) / kubelet_volume_stats_capacity_bytes)*100)>bool $capacity)"
    }
   ]
  },
  {
   "title": "List of PVCs > $capacity% used",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 3 },
   "targets": [
    {
     "expr": "((kubelet_volume_stats_capacity_bytes-kubelet_volume_stats_available_bytes) / kubelet_volume_stats_capacity_bytes * 100)>$capacity"
    }
   ]
  },
  {
   "title": "Number of Unbound PVCs",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_persistentvolumeclaim_status_phase{phase=\"Bound\"}!=bool 1)"
    }
   ]
  },
  {
   "title": "Unbound PVCs",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 3 },
   "targets": [
    {
     "expr": "kube_persistentvolumeclaim_status_phase{phase=\"Bound\", namespace=\"open-cluster-management-observability\"}!=1"
    }
   ]
  }
 ]
}